name: MacOS

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose --all-targets --examples
      - name: Run tests
        run: cargo test --verbose --no-fail-fast
      - name: Clippy
        run: cargo clippy
